spring:
  application:
    name: ragsystem
  ai:
    vectorstore:
      qdrant:
        api-key: ${QDRANT_API_KEY:}
        host: ${QDRANT_HOST:localhost}
        port: ${QDRANT_PORT:6334}
        use-tls: ${QDRANT_USE_TLS:false}
    embedding:
      provider: ${EMBED_PROVIDER:ollama}
    openai:
      api-key: ${OPENAI_API_KEY:sk-Oa6RAKhVLsUqHaa2YjPWvi72XO_Y2K-N}
      base-url: ${OPENAI_BASE_URL:https://routerai.ru/api}
      embedding:
        options:
          model: ${OPENAI_EMBED_MODEL:mistralai/codestral-embed-2505}
          encoding-format: float
    ollama:
      base-url: ${OLLAMA_URL:http://localhost:11434}
      embedding:
        options:
          model: ${OLLAMA_EMBED_MODEL:nomic-embed-text}
  datasource:
    url: ${POSTGRESQL_URL:jdbc:postgresql://localhost:5432/ragsystem}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
    open-in-view: false
services:
  task:
    cleanup_period_millis: ${TASK_CLEANUP_PERIOD:1000}
    permitted_count_synchronous_tasks: ${TASK_SIMULTANEOUS:10}
  retrieve:
    top_k: ${RETRIEVE_TOP_K:3}
    similarity_threshold: ${RETRIEVE_SIMILARITY_THRESHOLD:0.65}
    max_results: ${RETRIEVE_MAX_COUNT:3}
    context_chunks_before: ${RETRIEVE_RADIUS:1}
    context_chunks_after: ${RETRIEVE_RADIUS:1}
config:
  chunker:
    max_size: ${CHUNK_MAX_SIZE:700}
    min_payload_size: ${CHUNK_MIN_PAYLOAD:300}
    overlap: ${CHUNK_OVERLAP:0.1}
projects:
  root-path: ${user.home}/rag-system/projects




